# Generated by Django 4.1.7 on 2023-03-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_itemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='itemLink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='productName',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
