# Generated by Django 4.1.7 on 2023-03-08 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review_itemlink_review_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdByUser_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LikesOfUser_List', to=settings.AUTH_USER_MODEL)),
                ('onReview_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LikesOfPost_List', to='main.review')),
            ],
        ),
    ]
