# Generated by Django 4.1.7 on 2023-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(auto_created=0, default=8),
            preserve_default=False,
        ),
    ]
