# Generated by Django 4.1.7 on 2023-03-12 00:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_review_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.ChangeName.reviewImage),
        ),
    ]
