# Generated by Django 4.1.7 on 2023-03-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bioText',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
