# Generated by Django 4.1.7 on 2023-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_review_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='videoIsYT',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
