# Generated by Django 4.1.7 on 2023-06-27 18:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_review_videoisyt'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='disLikeCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
