# Generated by Django 4.1.7 on 2023-06-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likeCountVideo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='disLikeCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='LikeVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdByUser_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LikesOfVideoUser_List', to=settings.AUTH_USER_MODEL)),
                ('onReview_Key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LikesOfVideoPost_List', to='main.review')),
            ],
        ),
    ]
