# Generated by Django 4.1.7 on 2023-06-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_review_likecountvideo_alter_review_dislikecount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='createdByUser_key',
            new_name='createdByUser_Key',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='onReview_key',
            new_name='onReview_Key',
        ),
    ]
